export const CHANGE_ANSWERED_CATEGORY = 'CHANGE_ANSWERED_CATEGORY';
export const SET_CURRENT_QUESTION = 'SET_CURRENT_QUESTION';
export const FLIP_CARD = 'FLIP_CARD';
export const RESET_CARDS_IN_DECK_TO_QUESTION =
  'RESET_CARDS_IN_DECK_TO_QUESTION';
export const ADD_NEW_DECK = 'ADD_NEW_DECK';
export const ADD_NEW_CARD = 'ADD_NEW_CARD';
export const RESET_CARDS_TO_UNANSWERED = 'RESET_CARDS_TO_UNANSWERED';
export const HYDRATE_DECKS = 'HYDRATE_DECKS';
export const HYDRATE_NOTIFICATION_SETTINGS = 'HYDRATE_NOTIFICATION_SETTINGS';
export const TOGGLE_NOTIFICATIONS = 'TOGGLE_NOTIFICATIONS';
export const INCREMENT_QUESTIONS_ANSWERED = 'INCREMENT_QUESTIONS_ANSWERED';
export const RESET_QUESTIONS_ANSWERED = 'RESET_QUESTIONS_ANSWERED';
export const TOGGLE_CARD_ANSWERED = 'TOGGLE_CARD_ANSWERED';
